### ISSUE TITLE
not able to get the addon to stay running

### ISSUE THREAD

**Issue by Menz01** [BigThunderSR/homeassistant-addons-onstar2mqtt#707]
Hello,
    is this addon still working? i can't seem to get it to work. i followed the steps to generate a UUID and i filled in all the info on the config page, but the addon will not stay started and the logsdon't actually seem to be refreshing so i am not sure if the logs i am looking at are correct.

i am seeing this in the logs

"Request Failed with status 400 - Bad Request","request":

**Comment by almoney** [comment]
Still working for me. Double-check your configuration.

**Comment by Menz01** [comment]
> Still working for me. Double-check your configuration.

i have double, triple, quadruple checked and i do not understand what the issue is

**Comment by Menz01** [comment]
well i figured it out... i was using the older addon... i should not install things from my phone... i was not seeing all the versions when i did it from there
