### ISSUE TITLE
Homebridge-OnStar With New metheos TOTP Requirement

### ISSUE THREAD

**Issue by reartvapps** [BigThunderSR/homeassistant-addons-onstar2mqtt#824]
I have been working on this package for so long. I cannot figure out how to make this configuration work. It keeps returning with it not having all the necessary requirements can update the main-master of samrum/homebridge-onstar to be able for OnStar to work for everybody. I am a newbie and am just started to learn reverse engineering and have not acquired the skills to be able to update a package like this.

**Comment by Z1mDMan** [comment]
> I have been working on this package for so long. I cannot figure out how to make this configuration work. It keeps returning with it not having all the necessary requirements can update the main-master of samrum/homebridge-onstar to be able for OnStar to work for everybody. I am a newbie and am just started to learn reverse engineering and have not acquired the skills to be able to update a package like this.

Thank you for looking into this! I am following/testing your homebridge-onstar-dev plugin. I set everything up but getting this error on 1.0.2.  I'll mention it over there as well but wanted to ping here for more visibility.

[11/26/2024, 4:46:00 PM] [Malibu] Initializing OnStar accessory...
[11/26/2024, 4:46:00 PM] [Malibu] Config Error: Invalid or missing value for totpKey
[11/26/2024, 4:46:00 PM] [Malibu] Config Error: The provided configuration is not valid.
[11/26/2024, 4:46:00 PM] [Malibu] Accessory OnStar returned empty set of services; not adding it to the bridge.

I put in my TOTP secret from the chevy website that I captured the other day. Do I need to try and regenerate it there?

**Comment by reartvapps** [comment]
I haven't gotten past that part it keeps returning an error for me @BigThunderSR said he would look into it with me this weekend.

> > I have been working on this package for so long. I cannot figure out how to make this configuration work. It keeps returning with it not having all the necessary requirements can update the main-master of samrum/homebridge-onstar to be able for OnStar to work for everybody. I am a newbie and am just started to learn reverse engineering and have not acquired the skills to be able to update a package like this.
> 
> Thank you for looking into this! I am following/testing your homebridge-onstar-dev plugin. I set everything up but getting this error on 1.0.2. I was going to mention it over there as well but issues aren't enabled there.
> 
> [https://github.com/reartvapps/homebridge-onstar-dev](url)
> 
> [11/26/2024, 4:46:00 PM] [Malibu] Initializing OnStar accessory... [11/26/2024, 4:46:00 PM] [Malibu] Config Error: Invalid or missing value for totpKey [11/26/2024, 4:46:00 PM] [Malibu] Config Error: The provided configuration is not valid. [11/26/2024, 4:46:00 PM] [Malibu] Accessory OnStar returned empty set of services; not adding it to the bridge.
> 
> I put in my TOTP secret from the chevy website that I captured the other day. Do I need to try and regenerate it there?

**Comment by Z1mDMan** [comment]
> I haven't gotten past that part it keeps returning an error for me @BigThunderSR said he would look into it with me this weekend.
> 
> > > I have been working on this package for so long. I cannot figure out how to make this configuration work. It keeps returning with it not having all the necessary requirements can update the main-master of samrum/homebridge-onstar to be able for OnStar to work for everybody. I am a newbie and am just started to learn reverse engineering and have not acquired the skills to be able to update a package like this.
> > 
> > 
> > Thank you for looking into this! I am following/testing your homebridge-onstar-dev plugin. I set everything up but getting this error on 1.0.2. I was going to mention it over there as well but issues aren't enabled there.
> > [https://github.com/reartvapps/homebridge-onstar-dev](url)
> > [11/26/2024, 4:46:00 PM] [Malibu] Initializing OnStar accessory... [11/26/2024, 4:46:00 PM] [Malibu] Config Error: Invalid or missing value for totpKey [11/26/2024, 4:46:00 PM] [Malibu] Config Error: The provided configuration is not valid. [11/26/2024, 4:46:00 PM] [Malibu] Accessory OnStar returned empty set of services; not adding it to the bridge.
> > I put in my TOTP secret from the chevy website that I captured the other day. Do I need to try and regenerate it there?

sounds good. I will leave things as they are in my environment and available for testing/feedback. Thanks to both of you!

**Comment by reartvapps** [comment]
> I can try to take a look over the weekend, but no promises since I don't use/have access to HomeKit to do anything with Homebridge.

Could you let me know if you've been able to take a look yet?

**Comment by reartvapps** [comment]
@BigThunderSR can I add you as a collaborator because I don't know how you go from no dist folder to a dist folder with index.mjs and extra files with others being gone.

**Comment by reartvapps** [comment]
Yes I can

**Comment by reartvapps** [comment]
Got it to run, here is the error code

[12/1/2024, 8:08:20 PM] [GMC] unlockDoor: Requested
reqer
HTTP Error 302: Moved Temporarily
Response data: <html><head><title>Object moved</title></head><body>
<h2>Object moved to <a href="msauth.com.gm.mychevrolet%3a%2f%2fauth%2f%3ferror%3dserver_error%26error_description%3dAADB2C90255%253a%2bThe%2bclaims%2bexchange%2bspecified%2bin%2btechnical%2bprofile%2b%2527SelfAsserted-LocalAccountSignin-Email%2527%2bdid%2bnot%2bcomplete%2bas%2bexpected.%2bYou%2bmight%2bwant%2bto%2btry%2bstarting%2byour%2bsession%2bover%2bfrom%2bthe%2bbeginning.%250d%250aCorrelation%2bID%253a%2b8b39a4ad-3287-493e-84a0-0185add873ab%250d%250aTimestamp%253a%2b2024-12-02%2b01%253a08%253a22Z%250d%250a">here</a>.</h2>
</body></html>

Authentication failed: Error: Failed to extract csrf token or transId during MFA
    at GMAuth.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-onstar2/node_modules/onstarjs2/dist/index.mjs:34531:23)
    at Generator.next (<anonymous>)
    at fulfilled (file:///var/lib/homebridge/node_modules/homebridge-onstar2/node_modules/onstarjs2/dist/index.mjs:41:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/1/2024, 8:08:22 PM] [GMC] unlockDoor: Error: Failed to extract csrf token or transId during MFA

**Comment by reartvapps** [comment]
@BigThunderSR heres the code, it successfully ran and returned error:
[12/1/2024, 8:08:20 PM] [GMC] unlockDoor: Requested
reqer
HTTP Error 302: Moved Temporarily
Response data: <html><head><title>Object moved</title></head><body>
<h(2)>Object moved to <a href="msauth.com.gm.mychevrolet%3a%2f%2fauth%2f%3ferror%3dserver_error%26error_description%3dAADB2C90255%253a%2bThe%2bclaims%2bexchange%2bspecified%2bin%2btechnical%2bprofile%2b%2527SelfAsserted-LocalAccountSignin-Email%2527%2bdid%2bnot%2bcomplete%2bas%2bexpected.%2bYou%2bmight%2bwant%2bto%2btry%2bstarting%2byour%2bsession%2bover%2bfrom%2bthe%2bbeginning.%250d%250aCorrelation%2bID%253a%2b8b39a4ad-3287-493e-84a0-0185add873ab%250d%250aTimestamp%253a%2b2024-12-02%2b01%253a08%253a22Z%250d%250a">here</a>.</h(2)>
</body></html>

Authentication failed: Error: Failed to extract csrf token or transId during MFA
    at GMAuth.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-onstar2/node_modules/onstarjs2/dist/index.mjs:34531:23)
    at Generator.next (<anonymous>)
    at fulfilled (file:///var/lib/homebridge/node_modules/homebridge-onstar2/node_modules/onstarjs2/dist/index.mjs:41:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/1/2024, 8:08:22 PM] [GMC] unlockDoor: Error: Failed to extract csrf token or transId during MFA

I put extra parentheses around the h2 because it formatted automatically.

**Comment by reartvapps** [comment]
@BigThunderSR
It ran successfully, here is the error
[12/1/2024, 8:19:28 PM] [GMC] unlockDoor: Requested
Authentication failed: Error: Failed to get authorization code
    at GMAuth.<anonymous> (file:///var/lib/homebridge/node_modules/homebridge-onstar2/node_modules/onstarjs2/dist/index.mjs:34497:23)
    at Generator.next (<anonymous>)
    at fulfilled (file:///var/lib/homebridge/node_modules/homebridge-onstar2/node_modules/onstarjs2/dist/index.mjs:41:58)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
[12/1/2024, 8:19:31 PM] [GMC] unlockDoor: Error: Failed to get authorization code

**Comment by reartvapps** [comment]
Im an idiot I put my VIN in wrong this entire time, I put it in with my code, it was ran successful, I ran it with your code it also ran successful. Thanks for helping me see my clumsy mistake I will publish this to my main branch.

**Comment by reartvapps** [comment]
@BigThunderSR Thank you very much, I'm very excited to get this package up and running again!

**Comment by Z1mDMan** [comment]
> @BigThunderSR Im an idiot I put my VIN in wrong this entire time, I put it in with my code, it was ran successful, I ran it with your code it also ran successful. Thanks for helping me see my clumsy mistake I will publish this to my main branch.

I can confirm 1.0.5 working here as well. Exciting!

**Comment by clk50** [comment]
Looking forward to the repo update!

**Comment by reartvapps** [comment]
https://github.com/reartvapps/homebridge-onstar-dev

**Comment by clk50** [comment]
So to use this we need to manually copy files over ?  Great that its working but I was hoping there would be a new version available from the Samrum homebridge-onstar plugin where anyone could easily update it from 1.5.39 to say 1.5.40 with this included change…

**Comment by Z1mDMan** [comment]
> So to use this we need to manually copy files over ? Great that its working but I was hoping there would be a new version available from the Samrum homebridge-onstar plugin where anyone could easily update it from 1.5.39 to say 1.5.40 with this included change…

There is a new homebridge-OnStar plugin available based on the changes. It’s homebridge-OnStar-dev

**Comment by clk50** [comment]
Ok found it. Thanks for the help!
